GET  http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmZDY3MWIzYWM4MGRmNTFmYjQ0NWEiLCJlbWFpbCI6InBvdHRlckBnbWFpbC5jb20iLCJpYXQiOjE2ODQ1MDM4NjAsImV4cCI6MTY4NDUwNzQ2MH0.RDrxjT9w51QtFbnmXtuq-T8HCl3EP6ib927yAx9iesI HTTP/1.1

