GET  http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmZDY3MWIzYWM4MGRmNTFmYjQ0NWEiLCJlbWFpbCI6InBvdHRlckBnbWFpbC5jb20iLCJpYXQiOjE2ODQzNDU4NzIsImV4cCI6MTY4NDM0OTQ3Mn0.nYWxG6wqfsa4y44CSHGqV1rcHeudWcYi5-EeitshW30 HTTP/1.1

