DELETE  http://localhost:5000/api/tasks/6475f65b9e39f2ae4e5b644f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc1ZjY1NzllMzlmMmFlNGU1YjY0NGIiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2ODU0NzQ2OTEsImV4cCI6MTY4NTQ3NDc1MX0.Nxc6hhfhXF02GPq-nizx9b6_bWAsKt9oexOttdWs_VU